# Generated by Django 4.2.2 on 2023-06-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
