# Generated by Django 4.2.2 on 2023-06-17 16:45

import apps.plant_profile.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[apps.plant_profile.validators.name_first_letter_capital])),
                ('last_name', models.CharField(max_length=20, validators=[apps.plant_profile.validators.name_first_letter_capital])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
