# Generated by Django 4.2.2 on 2023-06-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant',
            new_name='Profile',
        ),
    ]
